- name: "install package Play"
  hosts: all
  become: yes
  remote_user: ubuntu
  become_method: sudo

  tasks:
    - name: Wait for SSH access
      ansible.builtin.wait_for:
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        port: 22
      vars:
        ansible_connection: local
      become: no
    
    # - name: "update apt-get"
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    
    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    
    - name: Create xfs filesystem on /dev/nvme1n1
      community.general.filesystem:
        fstype: xfs
        state: present
        dev: /dev/nvme1n1
    
    - name: Create xfs filesystem on /dev/nvme2n1
      community.general.filesystem:
        fstype: xfs
        state: present
        dev: /dev/nvme2n1

    - name: Mount /dev/nvme1n1 to /data
      ansible.posix.mount:
        state: mounted
        path: /data
        src: /dev/nvme1n1
        fstype: xfs
        opts: noatime

    - name: Mount /dev/nvme2n1 to /backup
      ansible.posix.mount:
        state: mounted
        path: /backup
        src: /dev/nvme2n1
        fstype: xfs
        opts: noatime

    - name: update sysctl.conf with vm.swappiness and vm.zone_reclaim_mode
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: 'vm.swappiness', value: '1' }
        - { name: 'vm.zone_reclaim_mode', value: '0' }

    - name: Set correct ulimits
      community.general.pam_limits:
        domain: "mongod"
        limit_type: "{{ item.type }}"
        limit_item: "{{ item.parameter }}"
        value: "{{ item.value }}"
      with_items:
        - { type: 'hard', parameter: 'fsize', value: 'unlimited' }
        - { type: 'soft', parameter: 'fsize', value: 'unlimited' }
        - { type: 'hard', parameter: 'cpu', value: 'unlimited' }
        - { type: 'soft', parameter: 'cpu', value: 'unlimited' }
        - { type: 'hard', parameter: 'as', value: 'unlimited' }
        - { type: 'soft', parameter: 'as', value: 'unlimited' }
        - { type: 'hard', parameter: 'memlock', value: 'unlimited' }
        - { type: 'soft', parameter: 'memlock', value: 'unlimited' }